# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
##url: http://zhangjinmiao.github.io
date_format: "ordinal"
title: 山川尽美
subtitle: "脚踏实地，勇往直前"
description: "本站是山川尽美的技术分享驿站，内容涉及Java后端技术：JVM、Spring Boot、Spring Cloud、高并发、多线程、微服务、架构设计、中间件使用等技术知识；还包括日常生活感悟、理财知识等"
keywords: Java,zjm,imzhang,itzjm,山川尽美,Spring,Spring Boot,Spring Cloud,Go
timezone: Asia/Shanghai
encoding: "utf-8"
favicon: favicon.ico 

repository: zhangjinmiao/zhangjinmiao.github.io
github_url: https://github.com/zhangjinmiao
#url: http://www.mminn.xyz
##enforce_ssl: mminn.xyz

# ---------------- #
#      Author      #
# ---------------- #
author: Zhang jinmiao
organization: ZRB, Inc.
organization_url: https://www.zhenrongbao.com/
github_username: zhangjinmiao
location: Beijing, China
email: itzhangjm@gmail.com

# ---------------- #
#      Jekyll      #
# ---------------- #
# Build settings
markdown: kramdown
kramdown:
    input: GFM
    enable_coderay: true
highlighter: rouge

source:      .
destination: ./_site

defaults: []
lsi: false
quiet: false
excerpt_separator: "\n\n"
#permalink: /:year/:month/:day/:title/
permalink: /:categories/:year/:month/:day/:title:output_ext
gems:
    - jekyll-github-metadata
    - rouge
    - kramdown
    #- jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-geo-pattern
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - Jekyll-tagging
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

paginate: 8
paginate_path: 'page:num'

# ---------------- #
#    Navigation    #
# ---------------- #
# Navigation. top menu list
menus:

  #-
    #href: /zsxq.html
    #label: 星球
    #target: _self

  -
    href: /fuli.html
    label: 福利
    target: _self

  -
    href: /links/
    label: 链接

  -
    href: /used-urls/
    label: 网址
  
  -
    href: /money.html
    label: 挣钱
    target: _blank

  -
    href: /todo.html
    label: TODO
    target: _blank
  
  -
    href: /links/
    label: 链接

# Navigation. main menu list    
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /fuli.html
    label: 福利
    target: _blank

  -
    href: /open-source/
    label: 开源

  -
    href: /used-urls/
    label: 网址

  -
    href: /about.html
    label: 关于



# labels. my blog key words
labels:

  -
    href: /payment.html
    label: 支付
    target: _self

# selected articles
classes:

  -
    href: /life.html
    name: 我的故事
    describe: 生活就是故事，故事就是生活

# ---------------- #
#       RSS        #
# ---------------- #
#subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 4 # Number of repos to show

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
# comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
# gitment:
    #owner: zhangjinmiao
    #repo: blog-comments
    #oauth:
        #client_id: e5745b9f2c046ee0c357
        #client_secret: 65a695b992dc36811f6cf752593994ffbb1316c6
# https://github.com/gitalk/gitalk#install
#gitalk:
    #owner: zhangjinmiao
    #repo: blog-comments
    #clientID: e5745b9f2c046ee0c357
    #clientSecret: 65a695b992dc36811f6cf752593994ffbb1316c6
# 在使用其它评论组件时可点击显示 Disqus
#lazy_load_disqus : true

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
    #analytics_id: UA-80669434-1
